# matsushibadenki/snn4/configs/models/small.yaml
# 小規模なデバッグ・開発用モデルのアーキテクチャ設定

model:
  path: "breakthrough_snn_model_small.pth" # モデルごとに保存パスを分ける
  architecture_type: "predictive_coding" # "predictive_coding" または "spiking_transformer"
  d_model: 128
  d_state: 64
  num_layers: 4
  time_steps: 20
  n_head: 2
  # ニューロン設定
  neuron:
    type: "lif" # "lif" または "dendritic"
    # typeが "dendritic" の場合のみ使用されるパラメータ
    num_branches: 4
    branch_features: 32 # 例: d_model / num_branches